### ISSUE TITLE
Track misalignment after Zooming-in

### ISSUE THREAD

**Issue by proteinmechanic** [rcsb/rcsb-saguaro#32]
Hi, 

Apologies if this isn't the right place for this. 

In my work, when I load several tracks, sometimes they do not align perfectly. 

I have also now checked several of the examples online, and apparently some of them have the same issue. 

As an example see the selected column 80 in this screenshot. This is the implementation of the library on RCSB PDB. 

<img width="1161" alt="Screen Shot 2022-12-28 at 11 13 07 AM" src="https://user-images.githubusercontent.com/2698601/209751542-57016b2b-0c80-4418-a491-954c43b15689.png">

Can I please check if there is a fix? I think this only occurs when the track is zoomed-into and in certain cases. 

Using: 

MacOS 10.15.7
Safari 15.6

Any help on this would be highly appreciated. 

Apologies, again,  if this isn't the right place for this. Happy to re-post if redacted. 

Thank you. 
Regards, 
/A

**Comment by bioinsilico** [comment]
Thank you, @proteinmechanic, for reporting this bug, and I apologize for the delay in replying. This bug should be fixed in v2.5.8. Please, can you update rcsb-saguaro and check that the bug is fixed?

**Comment by proteinmechanic** [comment]
Thank you for your time on this. 

Unfortunately I still see this: 

![image](https://user-images.githubusercontent.com/2698601/213829835-e848313f-fa6d-4275-a07e-228571e5c0d5.png)

Just to clarify I use :: https://cdn.jsdelivr.net/npm/@rcsb/rcsb-saguaro/build/rcsb-saguaro.js

This should have v2.5.8 - right? 

Regards, 
Ashar

**Comment by bioinsilico** [comment]
Do you see the same bug in https://www.rcsb.org/sequence/1HV4? Can you try it openning a private session?

**Comment by proteinmechanic** [comment]
I am sorry - should have waited. 
I no longer see it in RCSB PDB and also my own deployment seems to be fixed now.  Everything works as expect. 

Thank you so much for your time.
